package com.centit.platform.vo;

/**
 * @author zhf
 */

public enum TableName {
    F_OS_INFO,F_OPTINFO,F_OPTDEF, WORK_GROUP,F_DATABASE_INFO,F_TABLE_OPT_RELATION,
    M_META_FORM_MODEL, Q_DATA_PACKET,Q_DATA_PACKET_PARAM,
    F_MD_TABLE,F_MD_COLUMN, F_MD_RELATION,F_MD_REL_DETAIL,
    WF_FLOW_DEFINE,WF_NODE,WF_TRANSITION,
    WF_FLOW_STAGE,WF_OPT_TEAM_ROLE,WF_OPT_VARIABLE_DEFINE,FILE_LIBRARY_INFO
}
