package com.centit.platform.Vo;

/**
 * @author zhf
 */

public enum TableName {
    M_APPLICATION_INFO,M_APPLICATION_TEAM_USERS,F_DATABASE_INFO,
    M_META_FORM_MODEL,F_GROUP_TABLE, Q_DATA_PACKET,Q_DATA_PACKET_PARAM,
    F_MD_TABLE,F_MD_COLUMN, F_MD_RELATION,F_MD_REL_DETAIL,
    WF_FLOW_DEFINE,WF_NODE,WF_TRANSITION,WF_OPTINFO,
    WF_FLOW_STAGE,WF_OPT_TEAM_ROLE,WF_OPT_VARIABLE_DEFINE,WF_OPTPAGE
}
